name: 🤖 Dependabot Automations

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [main, development]

permissions:
  pull-requests: write
  contents: write
  repository-projects: write

jobs:
  dependabot-automations:
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Dependabot PR Automations
    uses: Andrews-McMeel-Universal/reusable_workflows/.github/workflows/dependabot-automations.yaml@2
    with:
      autoApprove: true
      autoMerge: false

  required-checks:
    name: Required Checks
    runs-on: ubuntu-latest
    needs: [dependabot-automations]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
