name: 📄 Create Release Draft

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-release-draft:
    name: Draft Release Notes
    uses: Andrews-McMeel-Universal/reusable_workflows/.github/workflows/release-drafter.yaml@latest
    secrets:
      PAT_ACTION_CI: ${{ secrets.PAT_ACTION_CI }}