name: 🔄 Sync with template repository

on:
  schedule:
    - cron: 0 9 1 JAN,APR,JUL,OCT *
  workflow_dispatch:
    inputs:
      isdryrun:
        type: boolean
        description: Dry run
        default: false

jobs:
  repo-sync:
    name: Sync with template repository
    uses: Andrews-McMeel-Universal/reusable_workflows/.github/workflows/template-sync.yaml@latest
    with:
      isdryrun: ${{ inputs.isdryrun }}
    secrets:
      PAT_ACTION_CI: ${{ secrets.PAT_ACTION_CI }}

